# Dependabot configuration for SafePrompt
# Automatically checks for dependency updates and security vulnerabilities

version: 2
updates:
  # Dashboard dependencies (Next.js application)
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "dashboard"
    # Group minor and patch updates together
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    # Security updates always get their own PR
    versioning-strategy: increase

  # Website dependencies (Next.js application)
  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "website"
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    versioning-strategy: increase

  # Docs Site dependencies (Next.js application)
  - package-ecosystem: "npm"
    directory: "/docs-site"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "docs-site"
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    versioning-strategy: increase

  # API dependencies (Node.js application)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 5
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "api"
    groups:
      development-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        dependency-type: "production"
        update-types:
          - "patch"
    versioning-strategy: increase

  # Test suite dependencies
  - package-ecosystem: "npm"
    directory: "/test-suite"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "test-suite"
    groups:
      test-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 3
    reviewers:
      - "ianreboot"
    labels:
      - "dependencies"
      - "github-actions"
