name: Security Vulnerability
description: ⚠️ DO NOT use this for security issues - Email security@safeprompt.dev instead
title: "[Security]: Please email security@safeprompt.dev"
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ STOP - Do Not Report Security Issues Here

        **For security vulnerabilities, please DO NOT open a public GitHub issue.**

        ### How to Report Security Issues

        Email us directly at: **security@safeprompt.dev**

        Include in your email:
        - Description of the vulnerability
        - Steps to reproduce the issue
        - Potential impact
        - Any suggested fixes (optional)

        ### Why Email Instead of GitHub?

        - Public issues can be exploited before we have a chance to fix them
        - We need time to investigate and patch vulnerabilities
        - Responsible disclosure protects all SafePrompt users

        ### What to Expect

        - **Acknowledgment within 24 hours**
        - Regular updates on our progress
        - Credit in the fix announcement (if desired)
        - Coordinated public disclosure

        ### More Information

        See our full security policy: [SECURITY.md](https://github.com/ianreboot/safeprompt/blob/main/SECURITY.md)

        ---

        **If you're reporting a non-security bug, please close this issue and use the Bug Report template instead.**

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      options:
        - label: I understand that security issues should be emailed to security@safeprompt.dev
          required: true
        - label: I will close this issue and report via email instead
          required: true
