-- Phase 6.2.4: Add AI-specific columns to pattern_proposals
-- Adds columns for tracking AI-generated patterns and confidence scores

ALTER TABLE pattern_proposals
ADD COLUMN IF NOT EXISTS confidence_score REAL CHECK (confidence_score >= 0 AND confidence_score <= 1),
ADD COLUMN IF NOT EXISTS ai_generated BOOLEAN NOT NULL DEFAULT FALSE;

-- Index for AI-generated proposals
CREATE INDEX IF NOT EXISTS idx_pattern_proposals_ai_generated ON pattern_proposals(ai_generated);
CREATE INDEX IF NOT EXISTS idx_pattern_proposals_confidence ON pattern_proposals(confidence_score DESC);

COMMENT ON COLUMN pattern_proposals.confidence_score IS 'AI confidence score (0-1) for proposed patterns. Higher = more confident.';
COMMENT ON COLUMN pattern_proposals.ai_generated IS 'Whether this proposal was generated by AI analysis (true) or rule-based discovery (false)';
